package gui;

import city.AdministrativeArea;
import city.ResidentialArea;
import city.ShoppingArea;
import gui.CityMainFrame.OnCityControlActionListener;

/**
 *
 * @author Amira
 */
public class AddDistrictPanel extends javax.swing.JPanel {

    private AdministrativeArea admArea;
    private ShoppingArea comArea;
    private ResidentialArea resArea;
    private OnCityControlActionListener listener;

    public AddDistrictPanel(OnCityControlActionListener pListener) {
        admArea = new AdministrativeArea("administratif", 0, 0);
        comArea = new ShoppingArea("commercial", 0, 0);
        resArea = new ResidentialArea("résidentiel", 0, 0);
        listener = pListener;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddAreajLabel = new javax.swing.JLabel();
        AreaPricejLabel = new javax.swing.JLabel();
        XpositionjLabel = new javax.swing.JLabel();
        AreaTypejComboBox = new javax.swing.JComboBox<>();
        AreaTypejLabel1 = new javax.swing.JLabel();
        districtXPosComboBox = new javax.swing.JComboBox<>();
        ValidatejButton1 = new javax.swing.JButton();
        PricejLabel = new javax.swing.JLabel();
        districtYPosComboBox = new javax.swing.JComboBox<>();
        YpostionjLabel = new javax.swing.JLabel();

        AddAreajLabel.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        AddAreajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddAreajLabel.setText("Achat d'un quartier");

        AreaPricejLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        AreaPricejLabel.setText("Prix");

        XpositionjLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        XpositionjLabel.setText("Choisir X");

        AreaTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quartier Commercial", "Quartier Résidentiel", "Quartier Administratif" }));
        AreaTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTypejComboBoxActionPerformed(evt);
            }
        });

        AreaTypejLabel1.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        AreaTypejLabel1.setText("Type du quartier");

        districtXPosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        districtXPosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtXPosComboBoxActionPerformed(evt);
            }
        });

        ValidatejButton1.setText("Valider");
        ValidatejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidatejButton1ActionPerformed(evt);
            }
        });

        PricejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PricejLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        PricejLabel.setMaximumSize(new java.awt.Dimension(80, 20));
        PricejLabel.setMinimumSize(new java.awt.Dimension(80, 20));
        PricejLabel.setPreferredSize(new java.awt.Dimension(80, 20));
        PricejLabel.setSize(new java.awt.Dimension(45, 20));
        PricejLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PricejLabelPropertyChange(evt);
            }
        });

        districtYPosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        districtYPosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtYPosComboBoxActionPerformed(evt);
            }
        });

        YpostionjLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        YpostionjLabel.setText("Choisir Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddAreajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AreaTypejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(XpositionjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AreaPricejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YpostionjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ValidatejButton1)
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(districtXPosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AreaTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PricejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(districtYPosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 43, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(AddAreajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(XpositionjLabel)
                    .addComponent(districtXPosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(districtYPosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YpostionjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AreaTypejLabel1)
                    .addComponent(AreaTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AreaPricejLabel)
                    .addComponent(PricejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(ValidatejButton1)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AreaTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTypejComboBoxActionPerformed
        if (AreaTypejComboBox.getSelectedItem().equals("Quartier Administratif")) {
            PricejLabel.setText(String.valueOf(admArea.getPrice()));
        } else if (AreaTypejComboBox.getSelectedItem().equals("Quartier Commercial")) {
            PricejLabel.setText(String.valueOf(comArea.getPrice()));
        } else if (AreaTypejComboBox.getSelectedItem().equals("Quartier Résidentiel")) {
            PricejLabel.setText(String.valueOf(resArea.getPrice()));
        }
    }//GEN-LAST:event_AreaTypejComboBoxActionPerformed

    private void districtXPosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtXPosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtXPosComboBoxActionPerformed

    private void PricejLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PricejLabelPropertyChange


    }//GEN-LAST:event_PricejLabelPropertyChange

    private void ValidatejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidatejButton1ActionPerformed
        listener.onBuyDistrict(districtXPosComboBox.getSelectedIndex(), districtYPosComboBox.getSelectedIndex(), AreaTypejComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_ValidatejButton1ActionPerformed

    private void districtYPosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtYPosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtYPosComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddAreajLabel;
    private javax.swing.JLabel AreaPricejLabel;
    private javax.swing.JComboBox<String> AreaTypejComboBox;
    private javax.swing.JLabel AreaTypejLabel1;
    private javax.swing.JLabel PricejLabel;
    private javax.swing.JButton ValidatejButton1;
    private javax.swing.JLabel XpositionjLabel;
    private javax.swing.JLabel YpostionjLabel;
    private javax.swing.JComboBox<String> districtXPosComboBox;
    private javax.swing.JComboBox<String> districtYPosComboBox;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
