
package gui;

import gui.CityMainFrame.OnCityControlActionListener;

/**
 *
 * @author amira
 */
public class AddStationPanel extends javax.swing.JPanel {

    
    private OnCityControlActionListener listener;
    
    public AddStationPanel(OnCityControlActionListener pListener) {
        listener = pListener;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuyStationjLabel = new javax.swing.JLabel();
        XpositionjLabel = new javax.swing.JLabel();
        StationPricejLabel = new javax.swing.JLabel();
        YpostionjLabel = new javax.swing.JLabel();
        PricejLabel = new javax.swing.JLabel();
        XpositionjLabel1 = new javax.swing.JLabel();
        districtXPosComboBox = new javax.swing.JComboBox<>();
        districtYPosComboBox = new javax.swing.JComboBox<>();
        ValidatejLabel = new javax.swing.JButton();

        BuyStationjLabel.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        BuyStationjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuyStationjLabel.setText("Achat d'une station");

        XpositionjLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        XpositionjLabel.setText("Choisir X");

        StationPricejLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        StationPricejLabel.setText("Prix");

        YpostionjLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        YpostionjLabel.setText("Choisir Y");

        PricejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PricejLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        PricejLabel.setMaximumSize(new java.awt.Dimension(80, 20));
        PricejLabel.setMinimumSize(new java.awt.Dimension(80, 20));
        PricejLabel.setPreferredSize(new java.awt.Dimension(80, 20));
        PricejLabel.setSize(new java.awt.Dimension(45, 20));
        PricejLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PricejLabelPropertyChange(evt);
            }
        });

        XpositionjLabel1.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        XpositionjLabel1.setText("Veuillez choisir les coordonnées du quartier");

        districtXPosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        districtXPosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtXPosComboBoxActionPerformed(evt);
            }
        });

        districtYPosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        districtYPosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtYPosComboBoxActionPerformed(evt);
            }
        });

        ValidatejLabel.setText("Valider");
        ValidatejLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidatejLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(YpostionjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(districtYPosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StationPricejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PricejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(XpositionjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(districtXPosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BuyStationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(XpositionjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValidatejLabel)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BuyStationjLabel)
                .addGap(18, 18, 18)
                .addComponent(XpositionjLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(XpositionjLabel)
                            .addComponent(districtXPosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(YpostionjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(districtYPosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StationPricejLabel)
                    .addComponent(PricejLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ValidatejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PricejLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PricejLabelPropertyChange

    }//GEN-LAST:event_PricejLabelPropertyChange

    private void districtXPosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtXPosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtXPosComboBoxActionPerformed

    private void districtYPosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtYPosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtYPosComboBoxActionPerformed

    private void ValidatejLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidatejLabelActionPerformed
        listener.onAddStation(districtXPosComboBox.getSelectedIndex(), districtYPosComboBox.getSelectedIndex());
    }//GEN-LAST:event_ValidatejLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuyStationjLabel;
    private javax.swing.JLabel PricejLabel;
    private javax.swing.JLabel StationPricejLabel;
    private javax.swing.JButton ValidatejLabel;
    private javax.swing.JLabel XpositionjLabel;
    private javax.swing.JLabel XpositionjLabel1;
    private javax.swing.JLabel YpostionjLabel;
    private javax.swing.JComboBox<String> districtXPosComboBox;
    private javax.swing.JComboBox<String> districtYPosComboBox;
    // End of variables declaration//GEN-END:variables
}
